name: vargp
channels:
  - conda-forge
dependencies:
  - python=3.7
  - pip
  - pip:
    - jupyterlab
    - ipywidgets
    - seaborn
    - numpy
    - tqdm
    - fire
    - tensorboard
    - 'wandb<0.10'
    - torch
    - torchvision
    - torch_optimizer
