name: vargp
channels:
  - conda-forge
dependencies:
  - python<=3.9
  - pip
  - pip:
    - jupyterlab
    - ipywidgets
    - seaborn
    - numpy
    - tqdm
    - fire
    - tensorboard
    - wandb
    - torch==1.8.1
    - torchvision==0.9.1
    - torch_optimizer==0.1.0
